// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkxyucrvjwnjbcxqkord.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJreHl1Y3J2anduamJjeHFrb3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDkyMTAsImV4cCI6MjA3NDEyNTIxMH0.EO6cd6hvt8m0otC0PaT9Wu5vp-GHgmCe3tcSElZZ7ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});